# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'Koober' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Koober
  pod 'Koober_iOS', :path => '../Koober_iOS'
  pod 'KooberUIKit', :path => '../KooberUIKit'
  pod 'KooberKit', :path => '../KooberKit'

end
